### ISSUE TITLE
doesn't show up

### ISSUE THREAD

**Issue by 08Weber** [LIV/GorillaTagLIV#8]

**Comment by 08Weber** [comment]
wen i start the game nothing show up. have i missed somthing?

**Comment by 08Weber** [comment]
that menu is not showing

**Comment by 08Weber** [comment]
(sorry for bad English)

**Comment by 08Weber** [comment]
can i get a video tutorial of somone setting everything up?

**Comment by Raicuparta** [comment]
OK, I will make q video showing how it works soon.

**Comment by Raicuparta** [comment]
@08Weber In the meantime, I also added some better instructions on how to get LIV working. Please check the readme again and try to follow them. I'll try to make a video soon.

**Comment by Raicuparta** [comment]
I have added this video to the Readme: https://www.youtube.com/watch?v=x4KdwH6XBY4
It should help you set up LIV.
